language: python
before_install:
  - sudo apt-get install libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev tree
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so.8 /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
python:
  - "2.7"
script: nosetests